name: "Test hash-calculator-action"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      id: hash
      with:
        input: pplanel
        method: SHA512
        truncate: true
    - name: print output
      run: |
        echo This is the output ${{steps.hash.outputs.digest}}
